owner: Solidops-io
repo: upptime-postoaki

sites:
  - name: Api PostoAki
    url: https://redemeta.api.postoaki.com/health
  - name: Grafana
    url: https://grafana.postoaki.app

status-website:
  cname: upptime.postoaki.app
  logoUrl: https://solidops.io/wp-content/themes/solidops/images/logo-header.png
  introTitle: "**Upptime Solidops PostoAki** Este é um monitor de saúde de aplicações PostoAki mantidos por [solidops.io](https://solidops.io)"
  name: "Upptime"
  css: "#sapper > main > section:nth-child(8) {visibility: hidden}"
  
  i18n:
    footer: This page is a [Solidops.io](https://solidops.io) page.
